baseurl = "https://alisonjoe.github.io/"
metaDataFormat = "yaml"
title = "Blist Multilingual Theme"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = " Looking Back at an Eclipsed Earth "
      introSubtitle = "  Here is what the Earth looks like during a.Theof the can be seen darkening part of.This  moved the at nearly 2000 kilometers per hour.Only  near the center of the see a total solar eclipse -others see a partial eclipse where only part of the.This  of the 1999 August 11was one of the last evertaken from the .The two bright spots that appear on the upper left are thought to be.Mir was  in a in 2001.A  will occur over  in about two weeks."
      introPhoto = "/nasa/CNES.jpg"
      logo = "/blist-logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2024 - alisonLai · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "giscus"

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""


[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true